name: healthyapps

services:
  hae-mongo:
    container_name: hae-mongo
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    networks:
      - hae_network
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

  hae-server:
    container_name: hae-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - READ_TOKEN=${READ_TOKEN}
      - WRITE_TOKEN=${WRITE_TOKEN}
    depends_on:
      - hae-mongo
    networks:
      - hae_network
    restart: unless-stopped

networks:
  hae_network:
    driver: bridge

volumes:
  mongodb-data:
